### ISSUE TITLE
FirebaseConnect.PlayerProfileFirebaseManager().getTotalScans() not found

### ISSUE THREAD

**Issue by fardeenfs** [CMPUT301W23T10/QRgo#105]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.qrgo, PID: 10813
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.example.qrgo.models.PlayerProfile.getTotalScans()' on a null object reference
        at com.example.qrgo.HomeActivity$3.onPlayerProfileGet(HomeActivity.java:110)
        at com.example.qrgo.firebase.PlayerProfileFirebaseManager.lambda$getPlayerProfile$4$com-example-qrgo-firebase-PlayerProfileFirebaseManager(PlayerProfileFirebaseManager.java:200)
        at com.example.qrgo.firebase.PlayerProfileFirebaseManager$$ExternalSyntheticLambda18.onComplete(Unknown Source:6)
        at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by fardeenfs** [comment]
Firebase rules updated. Issue seems to have been resolved.
